version: '3.4'

services:
    catalogdb:
        container_name: catalogdb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site/data/db
        ports:
            - "27017:27017"

    basketdb:
        container_name: basketdb
        restart: always
        ports:
            - "6379:6379"

    orderdb:
        container_name: orderdb
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Sa@12345678"
            ACCEPT_EULA: "Y"

    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
    
    catalog.api:
        container_name: catalogapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            # - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_URLS=http://+:80
            - "CatalogDatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
        depends_on:
            - catalogdb
        ports:
            - "8800:80"
            # - "39001:443"
        volumes:
            # - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

    basket.api:
        container_name: basketapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            # - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_URLS=http://+:80
            - "ConnectionStrings__Redis=basketdb:6379"
            - "EventBus__HostName=rabbitmq"
        depends_on:
            - basketdb
            - rabbitmq
        ports:
            - "8801:80"
            # - "443"
        volumes:
            # - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

    ordering.api:
        container_name: orderingapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            # - ASPNETCORE_URLS=https://+:443;http://+:80
            - "ConnectionStrings__OrderConnection=Server=orderdb;Database=OrderDb;User Id=sa;Password=Sa@12345678"
            - "EventBus__HostName=rabbitmq"
        depends_on:
            - orderdb
            - rabbitmq
        ports:
            - "8802:80"
            # - "443"
        volumes:
            # - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
